run:
  # concurrency: 2
  timeout: 5m
  skip-dirs:
    - example

linter-settings:
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  enable:
    - revive
    - goconst
    - gofmt
    - goimports
    - misspell
    - unparam
    - asasalint
    - bidichk
    - bodyclose
    - cyclop
    - decorder
    - dupl
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - ginkgolinter
    - gocheckcompilerdirectives
    - gocognit
    - gocritic
    - goerr113
    - goheader
    - gomoddirectives
    - lll

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck
